env=LANG,zh_CN.UTF-8
env=LC_ALL,C.UTF-8

env=SDL_IM_MODULE,fcitx
env=XMODIFIERS,@im=fcitx
env=GTK_IM_MODULE,fcitx
env=QT_IM_MODULE,fcitx

# Mihomo Party and common proxy environment variables.
env=http_proxy,http://127.0.0.1:7890
env=https_proxy,http://127.0.0.1:7890
env=all_proxy,http://127.0.0.1:7890

env=HTTP_PROXY,http://127.0.0.1:7890
env=HTTPS_PROXY,http://127.0.0.1:7890
env=ALL_PROXY,http://127.0.0.1:7890

env=no_proxy,127.0.0.1,localhost,::1
env=NO_PROXY,127.0.0.1,localhost,::1




# Static wallpaper; fill preserves aspect ratio and crops overflow.
exec-once=/opt/clash-party/mihomo-party
exec-once=fcitx5
exec-once=kanshi

exec-once=setpriv --pdeathsig TERM noctalia

exec-once=sh -c 'echo "Xft.dpi: 120" | xrdb -merge'
