# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x1a1b26ff
rootcolor = 0x24283bff
bordercolor = 0x66709bff
dropcolor = 0x7aa2f780
splitcolor = 0x73dacaff
focuscolor = 0x7aa2f7ff
maximizescreencolor = 0xbb9af7ff
urgentcolor = 0xf7768eff
scratchpadcolor = 0x73dacaff
globalcolor = 0x0940b5ff
overlaycolor = 0x530ed1ff
jump_label_decorate_fg_color = 0xc0caf5ff
jump_label_decorate_bg_color = 0x272c42ff
jump_label_decorate_focus_fg_color = 0x1a1b26ff
jump_label_decorate_focus_bg_color = 0x7aa2f7ff
jump_label_decorate_border_color = 0x66709bff
group_bar_decorate_fg_color = 0xc0caf5ff
group_bar_decorate_bg_color = 0x272c42ff
group_bar_decorate_focus_fg_color = 0x1a1b26ff
group_bar_decorate_focus_bg_color = 0x7aa2f7ff
group_bar_decorate_border_color = 0x66709bff
