# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x232136ff
bordercolor = 0x6c6a85ff
dropcolor = 0xc4a7e780
splitcolor = 0x9ccfd8ff
focuscolor = 0xc4a7e7ff
maximizescreencolor = 0xf6c177ff
urgentcolor = 0xeb6f92ff
scratchpadcolor = 0x9ccfd8ff
globalcolor = 0x6728b4ff
overlaycolor = 0xb16b0aff
jump_label_decorate_fg_color = 0xe0def4ff
jump_label_decorate_bg_color = 0x423d5eff
jump_label_decorate_focus_fg_color = 0x232136ff
jump_label_decorate_focus_bg_color = 0xc4a7e7ff
jump_label_decorate_border_color = 0x6c6a85ff
group_bar_decorate_fg_color = 0xe0def4ff
group_bar_decorate_bg_color = 0x423d5eff
group_bar_decorate_focus_fg_color = 0x232136ff
group_bar_decorate_focus_bg_color = 0xc4a7e7ff
group_bar_decorate_border_color = 0x6c6a85ff
