
# shell launcher and terminal
bind=SUPER,space,spawn,noctalia msg panel-toggle launcher
bind=SUPER,comma,spawn,noctalia msg settings-toggle
bind=SUPER,Return,spawn,kitty

bind=SUPER,E,spawn,kitty --class float

# noctalia
#
bind=SUPER+SHIFT,A,spawn,noctalia msg screenshot-fullscreen
bind=SUPER+SHIFT,S,spawn,noctalia msg screenshot-region
bind=SUPER,V,spawn,noctalia msg panel-toggle clipboard
bind=SUPER+SHIFT,C,spawn,hyprpicker -a



